services:
  moodle:
    image: erseco/alpine-moodle
    ports:
      - 80:8080
    environment:
      DB_TYPE: mariadb
      DB_HOST: mariadb
      DB_NAME: moodle
      DB_USER: moodle
      DB_PASS: moodle
      DB_PORT: 3306
      DB_PREFIX: mdl_
      DEBUG: "true"
      MOODLE_EMAIL: ${TEST_USER_EMAIL}
      MOODLE_LANGUAGE: es
      MOODLE_SITENAME: Moodle-eXeLearning
      MOODLE_USERNAME: ${TEST_USER_USERNAME}
      MOODLE_PASSWORD: ${TEST_USER_PASSWORD}
      PRE_CONFIGURE_COMMANDS: |
        echo 'This is a pre-configure command'
      POST_CONFIGURE_COMMANDS: |
        echo 'This is a post-configure command'
        echo 'Forcing upgrade to re-install exe plugin...'
        php admin/cli/upgrade.php --non-interactive
    depends_on:
      - mariadb
    volumes:
      - moodledata:/var/moodledata
      - .:/var/www/html/repository/omeka
  mariadb:
    image: mariadb:10.11
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    volumes:
      - dbdata:/var/lib/mysql

  omekas:
    image: ghcr.io/erseco/omeka-s-docker:master
    restart: unless-stopped
    ports:
      - 81:80
    volumes:
      - omekas_data:/var/www/html/volume:Z
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
      MYSQL_HOST: mariadb
      APPLICATION_ENV: development
      OMEKA_THEMES: https://github.com/omeka-s-themes/default/releases/download/v1.9.1/theme-default-v1.9.1.zip
      OMEKA_MODULES: |
        https://github.com/Daniel-KM/Omeka-S-module-Common/releases/download/3.4.66/Common-3.4.66.zip      
        https://github.com/Daniel-KM/Omeka-S-module-EasyAdmin/releases/download/3.4.29/EasyAdmin-3.4.29.zip
        https://github.com/Daniel-KM/Omeka-S-module-Adminer/releases/download/3.4.5-4.8.4/Adminer-3.4.5-4.8.4.zip
        https://github.com/ateeducacion/omeka-s-ThreeDViewer/releases/download/v1.0.4/ThreeDViewer-v1.0.4.zip
        https://github.com/ateeducacion/OmekaS-LearningObject/releases/download/v1.0.0/LearningObjectAdapter-v1.0.0.zip

volumes:
  moodledata:
  dbdata:
  omekas_data:
